site_name: QuantEx
site_description: Documentation for QuantEx
theme:
  name: material
nav:
  - Home: index.md
  - Quick-Start: quickstart.md
  - Key Concepts: concepts.md
  - Roadmap: roadmap.md
  - API Reference:
      - Models: reference/quantex.models.md
      - Sources: reference/quantex.sources.md
      - Strategy: reference/quantex.strategy.md
      - Engine: reference/quantex.engine.md
      - Execution: reference/quantex.execution.md
      - Backtest: reference/quantex.backtest.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - ./src
          options:
            docstring_style: google