site_name: QuantEx
site_description: Documentation for QuantEx
theme:
  name: material
  palette:
    # Scheme can be 'default' (light) or 'slate' (dark)
    # You can also define specific light/dark palettes
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal # Example: Change the primary color (header, links)
      accent: deep orange # Example: Change the accent color (highlight)
      toggle:
        icon: material/brightness-4 # Icon for light mode
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # Or 'default' for a dark scheme
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7 # Icon for dark mode
        name: Switch to light mode
nav:
  - Home: index.md
  - Guides:
      - Strategies: usage/strategy.md
      - Data Sources: usage/data-sources.md
      - Backtesting Engine: usage/backtesting.md
      - Execution Simulator: usage/execution.md
      - Technical Indicators: usage/indicators.md
  - API Reference:
      - Models: reference/quantex.models.md
      - Sources: reference/quantex.sources.md
      - Strategy: reference/quantex.strategy.md
      - Engine: reference/quantex.engine.md
      - Execution: reference/quantex.execution.md
      - Backtest: reference/quantex.backtest.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - ./src
          options:
            docstring_style: google
  - mermaid2
  - print-site