"""quantex.execution — Execution utilities.

This module implements *ImmediateFillSimulator*, a zero-latency execution
engine used by the Quantex backtesting framework.

ImmediateFillSimulator converts strategy-generated `quantex.models.Order`
objects directly into `quantex.models.Fill` objects at the supplied
execution price, then updates the provided `quantex.models.Portfolio` so
metrics such as positions, cash, and equity remain consistent during a
backtest.

Key characteristics:
    * **Immediate fills** – no market latency, orders are filled in the
      same timestamp they are received.
    * **Configurable commission** – per-fill commission (default *0.0*) to
      approximate transaction costs. Slippage is currently assumed to be
      zero but can be incorporated in future extensions.

This concise implementation serves as a reference template; more
sophisticated execution models (e.g., with latency, partial fills, or
order books) can inherit from or replace this class in future versions.
"""

from __future__ import annotations

from datetime import datetime

from quantex.models import Fill, Order, Portfolio


class ImmediateFillSimulator:
    """Immediate (zero-latency) execution simulator.

    Converts incoming `quantex.models.Order` objects into
    `quantex.models.Fill` objects *instantly* at the supplied execution
    price. Commission and slippage are currently fixed to *zero* but the
    constructor exposes a *commission* argument so users can override the
    default behaviour in future iterations.
    """

    def __init__(self, portfolio: Portfolio, commission: float = 0.0) -> None:
        """Initializes the ImmediateFillSimulator.

        Args:
            portfolio: The portfolio to update upon fill.
            commission: The commission to apply to each fill.
        """
        self.portfolio = portfolio
        self.commission = commission

    def execute(
        self, order: Order, execution_price: float, timestamp: datetime
    ) -> Fill:
        """Converts order into a Fill and updates the portfolio.

        Args:
            order: The order generated by the strategy.
            execution_price: The price used for the fill.
            timestamp: Timestamp for the resulting `quantex.models.Fill`.

        Returns:
            The created Fill object.
        """

        if order.side == "buy":
            required_cash = order.quantity * execution_price + self.commission
            if required_cash > self.portfolio.cash:
                raise ValueError(
                    "Insufficient cash to execute buy order: "
                    f"required={required_cash:.2f}, available={self.portfolio.cash:.2f}"
                )

        signed_qty = order.quantity if order.side == "buy" else -order.quantity

        fill = Fill(
            order_id=order.id,
            symbol=order.symbol,
            quantity=signed_qty,
            price=execution_price,
            timestamp=timestamp,
            commission=self.commission,
        )

        # Immediately reflect the fill in the portfolio.
        self.portfolio.process_fill(fill)
        return fill
