from __future__ import annotations

from datetime import datetime

from quantex.models import Fill, Order, Portfolio


class ImmediateFillSimulator:
    """Immediate (zero-latency) execution simulator.

    Converts incoming `quantex.models.Order` objects into
    `quantex.models.Fill` objects *instantly* at the supplied execution
    price. Commission and slippage are currently fixed to *zero* but the
    constructor exposes a *commission* argument so users can override the
    default behaviour in future iterations.
    """

    def __init__(self, portfolio: Portfolio, commission: float = 0.0) -> None:
        """Initializes the ImmediateFillSimulator.

        Args:
            portfolio: The portfolio to update upon fill.
            commission: The commission to apply to each fill.
        """
        self.portfolio = portfolio
        self.commission = commission

    def execute(
        self, order: Order, execution_price: float, timestamp: datetime
    ) -> Fill:
        """Converts order into a Fill and updates the portfolio.

        Args:
            order: The order generated by the strategy.
            execution_price: The price used for the fill.
            timestamp: Timestamp for the resulting `quantex.models.Fill`.

        Returns:
            The created Fill object.
        """

        signed_qty = order.quantity if order.side == "buy" else -order.quantity

        fill = Fill(
            order_id=order.id,
            symbol=order.symbol,
            quantity=signed_qty,
            price=execution_price,
            timestamp=timestamp,
            commission=self.commission,
        )

        # Immediately reflect the fill in the portfolio.
        self.portfolio.process_fill(fill)
        return fill
